version: "3.8"
services:
  app:
    container_name: app
    build:
      context: ./direct_home_app
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./direct_home_app/:/direct_home_app/
  api:
    container_name: api
    build:
      context: ./direct_home_api
      dockerfile: Dockerfile
    ports: 
      - "8000:8000"
    volumes: 
      - ./direct_home_api/:/direct_home_api/
    depends_on: 
      - db
  db:
    container_name: db
    image: mysql:8.0.22
    volumes: 
      - db_volume:/var/lib/mysql
    ports:
      - "6038:3306"
    environment: 
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: direct_home_dev

volumes:
  db_volume:
