version: "3.3"
services:
  app:
    container_name: app
    build:
      context: ./direct_home_app
      dockerfile: Dockerfile
    environment:
      CHOKIDAR_USEPOLLING: "true"
    ports:
      - "3000:3000"
    volumes:
      - ./direct_home_app/:/app/
      - /app/node_modules/
    stdin_open: true
  api:
    container_name: api
    build:
      context: ./direct_home_api
      dockerfile: Dockerfile
    ports: 
      - "4000:4000"
    volumes: 
      - ./direct_home_api/:/app/
      - /app/_build/
      - /app/deps/
    depends_on: 
      - db
  db:
    container_name: db
    image: postgres:13.1
    volumes: 
      - pg_data:/var/lib/postgresql/data
    ports:
      - "2345:5432"
    environment: 
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: direct_home_api_dev

volumes:
  pg_data:
