version: "3.8"
services:
  app:
    build:
      context: ./direct_home_app
      dockerfile: Dockerfile
    environment:
      CHOKIDAR_USEPOLLING: "true"
    ports:
      - "3000:3000"
    volumes:
      - ./direct_home_app/:/app/
      - /app/node_modules/
  api:
    build:
      context: ./direct_home_api
      dockerfile: Dockerfile
    ports: 
      - "8000:8000"
    volumes: 
      - ./direct_home_api/:/var/www/html/
      - /var/www/html/vendor/
    depends_on: 
      - db
  db:
    image: mysql:8.0.22
    volumes: 
      - db_volume:/var/lib/mysql
    ports:
      - "6038:3306"
    environment: 
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: direct_home_dev

volumes:
  db_volume:
